# Generated by Django 4.1.7 on 2023-03-17 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_weatherstats'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='weatherdata',
            table='weather_data',
        ),
        migrations.AlterModelTable(
            name='weatherstats',
            table='weather_stats',
        ),
    ]
